# Site settings
title: Test Websit for my blogs.
description: It's description
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Udit Gulati
user_description: First year undergrad at IIIT UNA. Competitve programmer and an amateur blogger.
user_title: Competitive programmer
email: uditgulati0@gmail.com
github_username:  uditgulati

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
